import { Space_Grotesk } from "next/font/google";

import "./globals.css";
import Navbar from "../components/Navbar";

const space_grotesk = Space_Grotesk({ subsets: ["latin"] });

// export const metadata = {
//   title: "QKC Studios",
//   description: "qkc studios clothing",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <title>Quiet Kids Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <link rel="icon" href="/next.svg" />
      </head>
      <body
        className={`${space_grotesk.className} subpixel-antialiased bg-black text-[#f2f2f2]`}
      >
          {children}
      </body>
    </html>
  );
}
