import Image from "next/image";
import { Inter } from "next/font/google";

import { getProducts } from "../utils/shopify";
import Head from "next/head";
import { Key } from "react";
import ProductCard from "@/components/ProductCard";

const inter = Inter({ subsets: ["latin"] });

async function getData() {
  const data = await getProducts();

  if (!data.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to fetch data");
  }

  return data.json();
}

export default async function Home() {
  const data = await getProducts();
  const products = data.products.edges;

  console.log(products);

  return (
    <>
      <Head>
        <title>QKC STUDIOS | HOME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex">
          <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30">
            <code className="font-mono">QKC STUDIOS</code>
          </p>
        </div>
        <div className="max-w-2xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
          <div className="grid grid-cols-1 gap-y-10 sm:grid-cols-2 gap-x-6 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
          {products.map((product: { node: { id: Key | null | undefined } }) => {
            return <ProductCard key={product.node.id} product={product} />;
          })}
          </div>
        </div>
      </main>
    </>
  );
}
